In [2]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [3]:
from fastai.imports import *

from fastai.transforms import *
from fastai.conv_learner import *
from fastai.model import *
from fastai.dataset import *
from fastai.sgdr import *
from fastai.plots import *

In [4]:
PATH = "data/hwd/"
sz=224
arch=resnet34
bs=64

In [5]:

import os

def list_files(startpath):
    for root, dirs, files in os.walk(startpath):
        level = root.replace(startpath, '').count(os.sep)
        indent = ' ' * 4 * (level)
        print('{}{}/'.format(indent, os.path.basename(root)))
        subindent = ' ' * 4 * (level + 1)
        #for f in files:
            #print('{}{}'.format(subindent, f))


In [6]:
PATH = "data/hwd/"
list_files(PATH)

/
test/
.ipynb_checkpoints/
valid/
    6/
    9/
    7/
    1/
    5/
    4/
    0/
    2/
    8/
    3/
train/
    6/
    .ipynb_checkpoints/
    9/
    7/
    1/
    5/
    4/
    0/
    2/
    8/
    3/
models/
tmp/
    x_act_test_resnet34_0_224.bc/
        meta/
        data/
    x_act_val_resnet34_0_224.bc/
        meta/
        data/
    x_act_resnet34_0_224.bc/
        meta/
        data/


In [5]:
data = ImageClassifierData.from_paths(PATH, tfms=tfms_from_model(arch, sz))

In [6]:
learn = ConvLearner.pretrained(arch, data, precompute=True)

In [7]:
learn.fit(0.01, 3, cycle_len=1)

HBox(children=(IntProgress(value=0, description='Epoch', max=3), HTML(value='')))

[ 0.       0.26754  9.10068  0.00408]                        
[  1.        0.22019  10.41173   0.00338]                    
[  2.        0.18755  10.81627   0.00303]                    



In [12]:
log_preds,y = learn.TTA()
probs = np.mean(np.exp(log_preds), axis=0)
#metrics.log_loss(y, np.exp(log_preds[:,1:])), accuracy(log_preds[:,1:],y)


In [13]:
log_preds

array([[[ -8.92906,  -0.00886, -10.36787, ...,  -9.19682,  -9.59502,  -9.44465],
        [ -9.97076,  -0.00127,  -9.71914, ..., -11.02994, -11.90639, -10.52658],
        [-11.44629,  -0.00051, -12.84641, ..., -14.21868,  -9.61252,  -7.92266],
        ..., 
        [-11.91037, -10.97996, -11.50749, ..., -11.09465,  -9.36309,  -0.00019],
        [-10.25551, -13.78734, -13.31952, ...,  -9.81339,  -8.20627,  -0.00087],
        [-12.01468, -11.96989, -11.92965, ..., -13.24583,  -9.81113,  -0.00008]],

       [[ -8.92906,  -0.00886, -10.36787, ...,  -9.19682,  -9.59502,  -9.44465],
        [ -9.97076,  -0.00127,  -9.71914, ..., -11.02994, -11.90639, -10.52658],
        [-11.44629,  -0.00051, -12.84641, ..., -14.21868,  -9.61252,  -7.92266],
        ..., 
        [-11.91037, -10.97996, -11.50749, ..., -11.09465,  -9.36309,  -0.00019],
        [-10.25551, -13.78734, -13.31952, ...,  -9.81339,  -8.20627,  -0.00087],
        [-12.01468, -11.96989, -11.92965, ..., -13.24583,  -9.81113,  -0.00008]

In [14]:
log_preds = learn.predict(is_test=False)
metrics.log_loss(y, np.exp(log_preds[:,1:])), accuracy(log_preds[:,1:],y)
probs = np.exp(log_preds)

In [ ]:
log_preds

In [11]:
probs[:9]

array([[ 0.00013,  0.99118,  0.00003,  0.00296,  0.0002 ,  0.00004,  0.00007,  0.00514,  0.0001 ,  0.00007,
         0.00008],
       [ 0.00005,  0.99873,  0.00006,  0.00001,  0.00003,  0.00002,  0.00026,  0.00079,  0.00002,  0.00001,
         0.00003],
       [ 0.00001,  0.99949,  0.     ,  0.00001,  0.00002,  0.     ,  0.00001,  0.00004,  0.     ,  0.00007,
         0.00036],
       [ 0.00004,  0.99595,  0.00001,  0.00027,  0.00129,  0.00009,  0.00006,  0.0022 ,  0.00001,  0.00008,
         0.     ],
       [ 0.     ,  0.99984,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.00014,  0.     ,  0.     ,
         0.00001],
       [ 0.00102,  0.96982,  0.00041,  0.00529,  0.00149,  0.00008,  0.00227,  0.00221,  0.00051,  0.01052,
         0.00638],
       [ 0.00001,  0.99978,  0.00001,  0.00001,  0.     ,  0.     ,  0.     ,  0.00017,  0.     ,  0.     ,
         0.00002],
       [ 0.00018,  0.97729,  0.00016,  0.00027,  0.00004,  0.00024,  0.00013,  0.02147,  0.00009,  0.00006,
   