In [1]:
%matplotlib inline
%reload_ext autoreload
%autoreload 2

In [2]:
from fastai.structured import *
from fastai.column_data import *
np.set_printoptions(threshold=50, edgeitems=20)

PATH='data/titanic/'

In [44]:
t = pd.read_csv(f'{PATH}train.csv', low_memory=False)

In [4]:
from IPython.display import HTML

In [21]:
display(t.head())

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [22]:
display(DataFrameSummary(t).summary())

PassengerId  Survived    Pclass    Name   Sex      Age     SibSp  \
count                891       891       891     NaN   NaN      714       891   
mean                 446  0.383838   2.30864     NaN   NaN  29.6991  0.523008   
std              257.354  0.486592  0.836071     NaN   NaN  14.5265   1.10274   
min                    1         0         1     NaN   NaN     0.42         0   
25%                223.5         0         2     NaN   NaN   20.125         0   
50%                  446         0         3     NaN   NaN       28         0   
75%                668.5         1         3     NaN   NaN       38         1   
max                  891         1         3     NaN   NaN       80         8   
counts               891       891       891     891   891      714       891   
uniques              891         2         3     891     2       88         7   
missing                0         0         0       0     0      177         0   
missing_perc          0%        0%        0%      0%    0%   19.87%        0%   
types            numeric      bool   numeric  unique  bool  numeric   numeric   

                 Parch       Ticket     Fare        Cabin     Embarked  
count              891          NaN      891          NaN          NaN  
mean          0.381594          NaN  32.2042          NaN          NaN  
std           0.806057          NaN  49.6934          NaN          NaN  
min                  0          NaN        0          NaN          NaN  
25%                  0          NaN   7.9104          NaN          NaN  
50%                  0          NaN  14.4542          NaN          NaN  
75%                  0          NaN       31          NaN          NaN  
max                  6          NaN  512.329          NaN          NaN  
counts             891          891      891          204          889  
uniques              7          681      248          147            3  
missing              0            0        0          687            2  
missing_perc        0%           0%       0%       77.10%        0.22%  
types          numeric  categorical  numeric  categorical  categorical

In [45]:
t['Sex'].replace({'male':0,'female':1},inplace=True)

In [24]:
display(t.head())

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [15]:
cat_vars=['Ticket','Cabin','Embarked']

In [27]:
t["Embarked"].describe()

count     889
unique      3
top         S
freq      644
Name: Embarked, dtype: object

In [30]:
set(t["Embarked"])

{'C', 'Q', 'S', nan}

In [69]:
t['Embarked'].replace({'C':0,'Q':1,'S':2},inplace=True)

In [33]:
set(t["Ticket"])

{'110152',
 '110413',
 '110465',
 '110564',
 '110813',
 '111240',
 '111320',
 '111361',
 '111369',
 '111426',
 '111427',
 '111428',
 '112050',
 '112052',
 '112053',
 '112058',
 '112059',
 '112277',
 '112379',
 '113028',
 '113043',
 '113050',
 '113051',
 '113055',
 '113056',
 '113059',
 '113501',
 '113503',
 '113505',
 '113509',
 '113510',
 '113514',
 '113572',
 '113760',
 '113767',
 '113773',
 '113776',
 '113781',
 '113783',
 '113784',
 '113786',
 '113787',
 '113788',
 '113789',
 '113792',
 '113794',
 '113796',
 '113798',
 '113800',
 '113803',
 '113804',
 '113806',
 '113807',
 '11668',
 '11751',
 '11752',
 '11753',
 '11755',
 '11765',
 '11767',
 '11769',
 '11771',
 '11774',
 '11813',
 '11967',
 '12233',
 '12460',
 '12749',
 '13049',
 '13213',
 '13214',
 '13502',
 '13507',
 '13509',
 '13567',
 '13568',
 '14311',
 '14312',
 '14313',
 '14973',
 '1601',
 '16966',
 '16988',
 '17421',
 '17453',
 '17463',
 '17464',
 '17465',
 '17466',
 '17474',
 '17764',
 '19877',
 '19928',
 '19943',
 '19947'

In [90]:
y=t['Survived'].astype('float32')
drop_elements = ['PassengerId', 'Name', 'Ticket', 'Cabin','Survived']
t = t.drop(drop_elements, axis = 1)


KeyError: 'Survived'

In [85]:
t['Embarked'] = t['Embarked'].fillna('2')
t['Age'] = t['Age'].fillna(t['Age'].mean()).astype('float32')
t=t.astype('float32')

In [55]:
t.describe()

Pclass         Sex         Age       SibSp       Parch        Fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     2.308642    0.352413   29.544332    0.523008    0.381594   32.204208
std      0.836071    0.477990   13.013778    1.102743    0.806057   49.693429
min      1.000000    0.000000    0.000000    0.000000    0.000000    0.000000
25%      2.000000    0.000000   22.000000    0.000000    0.000000    7.910400
50%      3.000000    0.000000   29.000000    0.000000    0.000000   14.454200
75%      3.000000    1.000000   35.000000    1.000000    0.000000   31.000000
max      3.000000    1.000000   80.000000    8.000000    6.000000  512.329200

In [66]:
label_csv=f'{PATH}train.csv'
n=len(list(open(label_csv)))-1
val_idxs=get_cv_idxs(n)

In [91]:
cat_vars=['Sex','Embarked']
y=y.astype('float32')

In [92]:
md = ColumnarModelData.from_data_frame(PATH, val_idxs,t,y ,cat_flds=cat_vars, bs=128,)

In [71]:
emb_szs=[(2,2),(3,2)]

In [93]:
m = md.get_learner(emb_szs, len(t.columns)-len(cat_vars),
                   0.04, 1, [1000,500], [0.001,0.01])
lr = 1e-3

In [96]:
def inv_y(a): return np.exp(a)
def exp_rmspe(y_pred, targ):
    targ = inv_y(targ)
    pct_var = (targ - inv_y(y_pred))/targ
    return math.sqrt((pct_var**2).mean())

In [104]:
m.fit(lr, 200)

HBox(children=(IntProgress(value=0, description='Epoch', max=200), HTML(value='')))

[ 0.       0.50862  0.28617]                     
[ 1.       0.36513  0.19631]                     
[ 2.       0.30258  0.18193]                     
[ 3.       0.26538  0.20344]                     
[ 4.       0.24297  0.18927]                     
[ 5.       0.22727  0.16532]                     
[ 6.       0.21604  0.17606]                     
[ 7.       0.20723  0.17779]                     
[ 8.       0.19953  0.15984]                     
[ 9.       0.19254  0.16136]                     
[ 10.        0.18529   0.169  ]                  
[ 11.        0.18032   0.15922]                  
[ 12.        0.17525   0.1515 ]                  
[ 13.        0.17053   0.15198]                  
[ 14.        0.16609   0.14969]                  
[ 15.        0.16241   0.15048]                  
[ 16.        0.15868   0.1523 ]                  
[ 17.        0.15644   0.14984]                  
[ 18.        0.15451   0.14895]                  
[ 19.        0.15269   0.14981]                  


[ 163.         0.12168    0.14313]               
[ 164.         0.12197    0.14798]               
[ 165.         0.12226    0.13747]               
[ 166.         0.12236    0.1458 ]               
[ 167.         0.12435    0.1477 ]               
[ 168.         0.12436    0.14373]               
[ 169.         0.12381    0.14993]               
[ 170.         0.12353    0.14653]               
[ 171.         0.12304    0.14394]               
[ 172.         0.12301    0.14835]               
[ 173.         0.12295    0.13881]               
[ 174.         0.12251    0.14188]               
[ 175.         0.12146    0.14647]               
[ 176.         0.12217    0.13978]               
[ 177.         0.12164    0.16016]               
[ 178.         0.12257    0.15556]               
[ 179.         0.12219    0.14439]               
[ 180.         0.12228    0.14047]               
[ 181.         0.12258    0.15028]               
[ 182.         0.12198    0.15334]               


In [105]:
x,y=m.predict_with_targs()

In [108]:
x,y

(array([[ 0.11955],
        [ 0.30545],
        [ 0.32737],
        [ 0.35504],
        [ 0.92064],
        [ 0.0865 ],
        [ 0.60418],
        [ 0.75732],
        [ 0.52964],
        [ 0.28064],
        [ 0.31646],
        [ 0.12158],
        [ 0.84728],
        [ 0.08221],
        [ 0.13155],
        [ 0.35107],
        [ 0.08221],
        [ 0.08221],
        [ 1.20493],
        [ 0.78423],
        ..., 
        [ 0.08221],
        [ 0.07541],
        [ 1.03473],
        [ 0.08221],
        [ 0.60118],
        [ 0.08221],
        [ 1.01635],
        [ 0.08221],
        [ 0.08221],
        [ 1.03219],
        [ 0.08221],
        [ 1.09413],
        [ 0.60281],
        [ 0.95108],
        [ 0.95332],
        [ 0.08221],
        [ 0.08221],
        [ 0.39993],
        [ 0.13412],
        [ 0.29104]], dtype=float32), array([[ 0.],
        [ 1.],
        [ 1.],
        [ 0.],
        [ 1.],
        [ 0.],
        [ 1.],
        [ 1.],
        [ 0.],
        [ 0.],
        [ 0.],
     